export const ErrorCodes = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  USER_BANNED: 'USER_BANNED',
  FORBIDDEN_PLATFORM_ROLE: 'FORBIDDEN_PLATFORM_ROLE',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  EXPERT_NOT_FOUND: 'EXPERT_NOT_FOUND',
  EXPERT_MEMBER_ALREADY_EXISTS: 'EXPERT_MEMBER_ALREADY_EXISTS',
  EXPERT_MEMBER_NOT_FOUND: 'EXPERT_MEMBER_NOT_FOUND',
  INVALID_EXPERT_MEMBER_ROLE: 'INVALID_EXPERT_MEMBER_ROLE',
  // Expert RBAC (Story 4.3)
  FORBIDDEN_EXPERT_ROLE: 'FORBIDDEN_EXPERT_ROLE',
  FORBIDDEN_EXPERT_COURSE_ACCESS: 'FORBIDDEN_EXPERT_COURSE_ACCESS',
  EXPERT_MEMBERSHIP_REQUIRED: 'EXPERT_MEMBERSHIP_REQUIRED',
  EXPERT_CONTEXT_REQUIRED: 'EXPERT_CONTEXT_REQUIRED',
  // Expert gating by subscription (Story 5.3)
  EXPERT_SUBSCRIPTION_INACTIVE: 'EXPERT_SUBSCRIPTION_INACTIVE',
  // Courses/Modules/Lessons (EPIC 6)
  COURSE_NOT_FOUND: 'COURSE_NOT_FOUND',
  COURSE_MODULE_NOT_FOUND: 'COURSE_MODULE_NOT_FOUND',
  LESSON_NOT_FOUND: 'LESSON_NOT_FOUND',
  COURSE_INVALID_STATUS: 'COURSE_INVALID_STATUS',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
